In [187]:
import numpy as np

In [188]:
# 特徴量データ読み込み
futureValues = np.loadtxt("./teacherdata/15featurevalue1107.csv", delimiter = ",")
futureValues = futureValues.astype(np.float32)

In [189]:
#ラベルデータ読み込み
labels = np.loadtxt("./teacherdata/15loglabel1107.csv", delimiter = ",")
labels = labels.astype(np.float32)

# 型確認
# print(labels.dtype)

In [191]:
from keras.layers import Activation
from keras.models import Sequential
from keras.layers import Dense, Conv1D
from keras.utils.np_utils import to_categorical
from keras.optimizers import RMSprop

In [192]:
# 訓練データと、評価データの分割
# 特徴行列を x、ラベルデータを y
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(futureValues, labels, train_size=0.8)

/home/kurasaki/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [178]:
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(813,)))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(15, activation='sigmoid'))
model.summary()

model.compile(loss='binary_crossentropy',
 optimizer=RMSprop(),
 metrics=['accuracy'])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_26 (Dense)             (None, 512)               416768    
_________________________________________________________________
dropout_5 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_27 (Dense)             (None, 512)               262656    
_________________________________________________________________
dropout_6 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_28 (Dense)             (None, 15)                7695      
Total params: 687,119
Trainable params: 687,119
Non-trainable params: 0
_________________________________________________________________


In [179]:
#学習の実行fit
history = model.fit(x_train, y_train,
 batch_size=1,
 epochs=1,
 verbose=1,
 validation_data=(x_test, y_test))

Train on 28 samples, validate on 8 samples
Epoch 1/1
28/28 [==============================] - 1s 46ms/step - loss: 0.0695 - acc: 0.9786 - val_loss: 0.0017 - val_acc: 1.0000


In [181]:
#評価
_, acc = model.evaluate(x_test,y_test)
print(acc)

8/8 [==============================] - 0s 22ms/step
1.0


In [183]:
#推定試し
preds = []
preds = model.predict(x_test) 
preds[preds>=0.9] = 1 
preds[preds<0.9] = 0 

print(preds)

[[1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [184]:
y_proba = model.predict(x_train)
print(y_proba)
for i in range(len(y_proba[0])):
    print(round(y_proba[1][i], 4))

[[1.00000000e+00 1.27342028e-12 1.22522923e-13 7.02429477e-12
  1.18423162e-11 1.78252638e-11 1.00000000e+00 3.79909049e-13
  1.07503529e-11 4.07501463e-12 6.77426431e-13 3.55918940e-12
  1.12325107e-13 1.56373677e-12 1.00000000e+00]
 [1.00000000e+00 1.27342028e-12 1.22522923e-13 7.02429477e-12
  1.18423162e-11 1.78252638e-11 1.00000000e+00 3.79909049e-13
  1.07503529e-11 4.07501463e-12 6.77426431e-13 3.55918940e-12
  1.12325107e-13 1.56373677e-12 1.00000000e+00]
 [1.00000000e+00 1.27342028e-12 1.22522923e-13 7.02429477e-12
  1.18423162e-11 1.78252638e-11 1.00000000e+00 3.79909049e-13
  1.07503529e-11 4.07501463e-12 6.77426431e-13 3.55918940e-12
  1.12325107e-13 1.56373677e-12 1.00000000e+00]
 [9.99999404e-01 7.09200890e-07 3.02496687e-07 1.29478440e-06
  3.36112498e-06 1.81818075e-06 9.99997854e-01 6.09944379e-07
  2.89587001e-06 7.58351348e-07 4.23111544e-07 2.87737339e-06
  3.43217863e-07 6.13604868e-07 9.99998212e-01]
 [1.00000000e+00 2.68556182e-08 8.69166250e-09 7.84614187e-08
  

In [ ]:
model.save_weights('minst_mlp_weights.h5')